In [29]:
import numpy as np

def imprint_patterns(weightMatrix, patterns):
    n = len(weightMatrix)
    for p in range(len(patterns)):
        for i in range(n):
            for j in range(n):
                if i != j:
                    weightMatrix[i, j] += (2 / n) * (patterns[p][i] * 2 - 1) * (patterns[p][j] * 2 - 1)
    return weightMatrix

def predict(weightMatrix, patternArray, max_iterations=100):
    n = len(weightMatrix)
    predicted_patterns = []
    
    for input_pattern in patternArray:
        for _ in range(max_iterations):
            old_pattern = input_pattern.copy()
            for i in range(n):
                hi = np.dot(weightMatrix[i], input_pattern)
                input_pattern[i] = 0 if hi < 0 else 1  # Change thresholding here
            if np.array_equal(input_pattern, old_pattern):
                break
        predicted_patterns.append(input_pattern)
    return np.array(predicted_patterns)

# Example usage
if __name__ == "__main__":
    # Define the initial weight matrix
    num_neurons = 4
    initial_weightMatrix = np.zeros((num_neurons, num_neurons))

    # Define some patterns
    patterns = [[1, 1, 0, 0], [0, 0, 1, 1], [1, 0, 1, 0]]  # Patterns as binary arrays of 0s and 1s

    # Imprint the patterns onto the weight matrix
    weightMatrix = imprint_patterns(initial_weightMatrix, patterns)
    print(weightMatrix)

    # Test the network with a noisy pattern
    noisy_pattern = [[1, 1, 1, 0], [1,1,1,1]]  # Noisy pattern as binary array of 0s and 1s
    predicted_pattern = predict(weightMatrix, noisy_pattern)
    print("Predicted Pattern:", predicted_pattern)


[[ 0.   0.5 -0.5 -1.5]
 [ 0.5  0.  -1.5 -0.5]
 [-0.5 -1.5  0.   0.5]
 [-1.5 -0.5  0.5  0. ]]
Predicted Pattern: [[1 1 0 0]
 [0 0 1 1]]
